### PR TITLE
Detect integer and non-integer (#435)

### PR DESCRIPTION
**Pull request by shanzez**

### CODE REVIEW

**Comment by luckyraul** [comment]
May be just revert as it was?

https://github.com/zulip/docker-zulip/commit/0d72546a4cb183c985de6d96873ac5508cfd3ce3

**Comment by shanzez** [comment]
Fine by me.  The original change was intentional to correct something, of course.  My suggested change will get us there.

**Comment by mhkarimi1383** [comment]
@shanzez
I think the regex is a bit problematic I have used another method here https://github.com/zulip/docker-zulip/pull/439

**Comment by shanzez** [comment]
@mhkarimi1383 I'm fine with whatever solution as long as it gets fixed 😊. I prefer regex, but not everyone does.  If you have a use-case that you think would not work, I'm interested.

**Pull request closed without merging**
