### PR TITLE
Always generate secrets and do so more safely

### PR DESCRIPTION
**Pull request by jeaye**
Firstly, we no long persist `zulip-secrets.conf` to the data directory. Since it's generated on every boot, we just keep it in `/etc` where Zulip wants it.

Secondly, we no longer replace the old secret's assignment in place, which had an assumption which prohibited at least ~ from being in the passphrase. Instead, we delete the assignment, if it's there, and append it to the config anew.

This addresses both #140 and #143.

### CODE REVIEW

**Comment by jeaye** [comment]
Any update on this, @timabbott?

**Comment by timabbott** [comment]
@jeaye sorry for the slow reply.  This isn't correct; we need the secrets to be persisted after boot (e.g. every user gets logged out if you rotate `secret_key`).  But `generate_secrets.py` is designed to be idempotent, so that running it twice will only add any new secrets that have been added to the Zulip project since the first time it was run.  

Probably the right answer will end up being to extend `generate_secrets.py` to have a `--environment` option, that causes it to rewrite the file, replacing secrets that are set in the environment with the values from the environment?

**Comment by jeaye** [comment]
> This isn't correct; we need some secrets to be persisted after boot (e.g. every user gets logged out if you rotate secret_key).

That behavior doesn't change with this. The value will be removed and added back, but it won't be different. I don't see why the actual *file* needs to persist, as long as the *values* do.

**Comment by timabbott** [comment]
It does!  Because some (auto-generated) secrets that aren't for interaction with other containers but need to be stable over time aren't present in the Docker environment file.  Things like `avatar_salt`.  We need to keep the model of exposing those generated secrets outside the container.

So either we need to move all of those secrets to the environment, which is painful from a UX perspective (users would need to generate like 5 long random strings), or we need to preserve the high-level model.

(BTW, we can use `crudini` to interact with the secrets file for editing; it's a lot cleaner)

**Comment by jeaye** [comment]
> So either we need to move all of those secrets to the environment, which is painful from a UX perspective (users would need to generate like 5 long random strings), or we need to preserve the high-level model.

I think we should do this. Docker Compose has built-in support for the `.env` file for exactly this; we should provide users with a script to run to generate new passphrases to put in `.env` and not assume that these are going to be within `docker-compose.yml`. I broke that down here: https://github.com/zulip/docker-zulip/issues/143

> (BTW, we can use crudini to interact with the secrets file for editing; it's a lot cleaner)

Agreed, that's a good solution. My delete + add approach was done because the `sed` substitution was assuming the passphrase didn't contain `~`, which was indeed not the case.

If we need to close this and handle this any other way, I think it should be with the `.env` file.

**Comment by timabbott** [comment]
@jeaye sorry for the slow reply; I've been quite sick the last few weeks :(.  

I'm about to merge a quick rework of the Docker secrets logic that uses `crudini` and has better semantics than before semantics we want (preserving secrets not declared in the environment, and overwriting others) and preserving the secrets file (since I think it is a useful part of doing backups).  We'll definitely want to do more here, and I like your proposal of having a `.env` file.  

We can continue discussion on clearing out the other problems on #143; that seems like a better place than this PR thread.  Thanks again for your work on this!

**Pull request closed without merging**
