### PR TITLE
Some improvements for Dockerfile

### PR DESCRIPTION
**Pull request by Savemech**
- Bump to Ubuntu Bionic
- Make use of `DEBIAN_FRONTEND=noninteractive`
- Install, and init locale not inside python script from travis
- Try to use poor's man solution to run this without log files, didn't work, see #176 
- Make look more readable
- Don't move tar-gz into layer, use unpacked from build stage

### CODE REVIEW

**Comment by timabbott** [comment]
@Savemech thanks for the contributions!  I think some of the changes (e.g. removing comments) are probably counterproductive for users who are not experts in using Docker.  Some of the other changes (e.g. readability improvements) seem nice and I'd be happy to integrate if they were in separate commits.  Would you be up for reorganizing this branch to start with the most easily mergable changes in separate commits (e.g. readability improvements) and do one commit per distinct fix?  

Check out our [GitHub guide](https://zulip.readthedocs.io/en/latest/git-guide.html) and [commit guidelines](https://zulip.readthedocs.io/en/latest/contributing/version-control.html) for more details.

**Comment by Savemech** [comment]
Add some comments, and maybe I would check some problems that highlighted, and find some way to improve size of resulting image(that bothers me a lot), because were building Zulip for every commit in master automatically and for now its average of ~45 mins

**Comment by Savemech** [comment]
bump

**Comment by andersk** [comment]
@Savemech If you want to help things along, follow the guidelines that Tim linked ([GitHub guide](https://zulip.readthedocs.io/en/latest/git-guide.html), [commit guidelines](https://zulip.readthedocs.io/en/latest/contributing/version-control.html)). For example, there could be one commit that just does the bump to bionic (with no other changes, except any that might be required for the bionic bump), one commit that just does the tar.gz changes, and so on. This is the organization we’ll need before we can merge anything, and it’s helpful during review.

`DEBIAN_FRONTEND=noninteractive` could be set using [`ARG`](https://docs.docker.com/engine/reference/builder/#arg) so it doesn’t need to be duplicated everywhere.

What was going wrong without the timezone configuration?

**Comment by timabbott** [comment]
Closing, since many of the changes are stale (we've since done them via other PRs) and others are not well separated.

Thanks for your work on this @Savemech!

**Pull request closed without merging**
