### PR TITLE
Enable authentication for memcached and Redis

### PR DESCRIPTION
**Pull request by andersk**
This requires zulip/zulip#13682. Don’t merge this until after that is released and the version here is bumped.

### CODE REVIEW

**Comment by timabbott** [comment]
These changes look good, though we should check if the README.md lists the passwords to edit somewhere that we should tweak.

Can you do a final test of 2.1.2 with this PR and then merge + release this project?

**Comment by andersk** [comment]
Updated `README.md`. Presumably `kubernetes/zulip-rc.yml` also wants updates…

**Comment by andersk** [comment]
Retested with 2.1.2, seems to work.

**Comment by ilanpillemer** [comment]
I noticed the Kubernetes yams is not updated to use the different Redis and memcached containers... should they be? Is that why the Kubernetes files are working as expected?

**Pull request merged**
