### PR TITLE
Update versions for Zulip Server 6.0

### PR DESCRIPTION
**Pull request by maltokyo**
Updating for Zulip v6.0

### CODE REVIEW

**Review by klardotsh — COMMENTED** [review]
Thanks for dropping by, and for submitting your first pull request! Happy to work with you to get this merged in.

1. First, go ahead and give this a rebase off of the latest `main` if you could. If you need rebase tips, [our Quick Start guide](https://zulip.readthedocs.io/en/latest/git/overview.html#quick-start-how-zulip-uses-git-and-github) links to [an excellent tutorial](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request).
2. Looks like there's still several straggling references to Zulip 5.7 even after your changes, which should also be updated (or in the case of the Kubernetes `CHANGELOG`, added to):

```
(woods) docker-zulip  » (4cd31ed...) » rg '5\.7'

README.md
9:* [**Docker Hub**](https://hub.docker.com/r/zulip/docker-zulip) (`docker pull zulip/docker-zulip:5.7-0`)

kubernetes/chart/zulip/Chart.yaml
15:appVersion: "5.7-0"

kubernetes/chart/zulip/README.md
3:![Version: 0.4.0](https://img.shields.io/badge/Version-0.4.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square) ![AppVersion: 5.7-0](https://img.shields.io/badge/AppVersion-5.7--0-informational?style=flat-square)
75:| image.tag | string | `"5.7-0"` | Zulip image tag (immutable tags are recommended) |

kubernetes/chart/zulip/values.yaml
18:  tag: "5.7-0"

kubernetes/chart/zulip/CHANGELOG.md
3:- Update Zulip Server to 5.7

kubernetes/manual/zulip-rc.yml
89:          image: zulip/docker-zulip:5.7-0
```

**Comment by maltokyo** [comment]
Thank you, I think I have done all, please check @klardotsh

**Comment by maltokyo** [comment]
Should we also use the chance to upgrade base image to `ubuntu:22.04`?

**Comment by klardotsh** [comment]
Looks like this still needs changes to the K8S changelog and README; I'll patch those in and give this a squash merge here momentarily. Thanks @maltokyo!

**Comment by maltokyo** [comment]
> Looks like this still needs changes to the K8S changelog and README; I'll patch those in and give this a squash merge here momentarily. Thanks @maltokyo!

Thanks!  Sorry, I could not see where I had missed edits in those files.  Yes please if you could help to close it, would appreciate it!  How about rebasing the image to 22.04 ubuntu?  Or not needed?

**Review by klardotsh — APPROVED** [review]
Handled the K8S Chart README update (it was just a straggling link where the text/image was already correct).

We don't currently support Ubuntu 22.04 for deployments, so no update to the base image just yet. I don't have an exact ETA of when we plan to support 22.04 LTS in an official capacity, but thankfully, we have a few years of playroom, with ~2.5 years of runway left on 20.04 LTS support.

Holding final review for @alexmv who might know of any hidden gotchas I'm not yet aware of in the 6.0 upgrade, but to my eye this looks good and ready for merge. Thanks again @maltokyo!

**Comment by maltokyo** [comment]
@klardotsh - Thank you!!! 

In this blog post: https://blog.zulip.com/2022/11/17/zulip-6-0-released/ it mentions Ubuntu 22.04 official support so I thought it would be fine. When you say it's not supported do you mean on dicker?

**Comment by klardotsh** [comment]
> @klardotsh - Thank you!!!
> 
> In this blog post: https://blog.zulip.com/2022/11/17/zulip-6-0-released/ it mentions Ubuntu 22.04 official support so I thought it would be fine. When you say it's not supported do you mean on dicker?

Oops, sorry, you're right, and I'm mistaken: 22.04 is good :heavy_check_mark:, 22.10 is the one we don't support (yet?) :x:). I'm just crossing some brain wires here from what I'd read.

Unless there's a strong argument otherwise, I'd recommend sticking to the plan of keeping base image on 20.04 for now anyway: this decouples our risk, as taking two years of OS updates in the same swing as updating to a new major revision of the app code would be a *lot* of change in one PR, and we're in a good position to defer that risk to later (what with the LTS window still ongoing for 20.04).

**Comment by demonych** [comment]
if I'm not mistaken, Zulip 6  Removed support for Debian 10 and PostgreSQL 10 due to their approaching end-of-life upstream.
but docker-compose.yml still reference to image "zulip/zulip-postgresql:10"
is it ok?

**Comment by klardotsh** [comment]
Upgrading PostgreSQL (to v14) is addressed in https://github.com/zulip/docker-zulip/pull/369.

**Comment by maltokyo** [comment]
@klardotsh - I testing the PD14 upgrade manually, and got an error.  I think we should wait until someone can help wth this one.  https://github.com/zulip/docker-zulip/pull/368#issuecomment-1326215249

**Comment by klardotsh** [comment]
Docs regarding how to upgrade existing DBs to PG14 were added in https://github.com/zulip/docker-zulip/pull/368; it's indeed a manual process.

**Comment by maltokyo** [comment]
PostgreSQL14 upgrade issue above https://github.com/zulip/docker-zulip/pull/374#issuecomment-1327444877 resolved.  No issue to move forward with this upgrade.

**Comment by alexmv** [comment]
This change looks fine on its own -- thank you, @maltokyo!  However, we have a couple other non-backwards-compatible changes we want to fold in (#369, #307) which would be very nice to roll into a 6.0 tag, so I'm going to hold off on merging this immediately.

**Comment by maltokyo** [comment]
@alexmv I see the other PRs were merged, anything we can help with?

**Comment by alexmv** [comment]
Given the two backwards-incompatible changes, we're adding more upgrading documentation.  Please give #376 a read through to make sure it makes sense.

**Comment by maltokyo** [comment]
I read through, the upgrade instructions are clear and I could follow each step. Could not find inconsistencies.

I would suggest to use a release rather than just a tag for this clearly stating some manual steps are needed.

**Pull request merged**
